# copyright: 2025 European Union
# license: LICENSE.txt
name: cmts_altimetry_applications
channels:
  - conda-forge
  - cmts
  - eumetsat
dependencies:
  # Core
  - conda-forge::bokeh
  - conda-forge::cartopy
  - conda-forge::cmocean
  - conda-forge::dask
  - conda-forge::distributed
  - conda-forge::hda
  - conda-forge::ipympl
  - conda-forge::ipywidgets
  - conda-forge::jupyterlab
  - conda-forge::matplotlib
  - conda-forge::netcdf4
  - conda-forge::python=3.13
  - conda-forge::scipy
  - conda-forge::xarray
  # External
  - cmts::eumartools
  - eumetsat::eumdac
  # Extension
  - conda-forge::copernicusmarine